services:
  - type: cron
    name: p2p-tasanator
    env: python
    plan: starter
    region: oregon
    schedule: "0 13-23,0-1 * * *"   # 9am–9pm VET, cada hora
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python guardartasas.py
