services:
  - type: worker
    name: tasanator-cron-worker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python -u cron_worker.py
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: America/Caracas
      # Opcional para probar una corrida al arrancar
      # - key: CRON_FORCE_RUN
      #   value: "1"
