services:
  # CRON: actualiza tasas (9am–9pm VET, cada hora)
  - type: cron
    name: tasanator-cron
    env: python
    pythonVersion: 3.10.13
    plan: starter
    region: oregon
    schedule: "0 13-23,0-1 * * *"      # 9am–9pm VET
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: python guardar_tasas.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: America/Caracas

  # WORKER: bot de Telegram 24/7
  - type: worker
    name: tasanator-bot
    env: python
    pythonVersion: 3.10.13
    plan: starter
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: python -u bot_telegram.py
    autoDeploy: true
    envVars:
      - key: TASANATOR_TOKEN
        sync: false
      - key: TASANATOR_USERNAME
        value: Tasanator_Bot
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: USUARIOS_AUTORIZADOS
        sync: false
      - key: USUARIO_LIMITADO
        sync: false
      - key: USUARIO_RESTRINGIDO
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: America/Caracas
